-- =============================================================================
-- Create email_tracking table
-- =============================================================================
-- Tracks email messages for deduplication and thread management.
-- This table was created manually in production; this migration captures
-- the schema so fresh deploys from migrations produce a complete database.
-- =============================================================================

CREATE TABLE IF NOT EXISTS email_tracking (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id VARCHAR(255),
    thread_id VARCHAR(255),
    tracking_type VARCHAR(50) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON TABLE email_tracking IS 'Tracks email messages for deduplication and thread management';
